---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install php8
  become: yes
  apt: pkg=php8.0 state=latest

- name: Install php8-cli
  become: yes
  apt: pkg=php8.0-cli state=latest

- name: Install php8-zip
  become: yes
  apt: pkg=php8.0-zip state=latest

- name: Install php8-mysql
  become: yes
  apt: pkg=php8.0-mysql state=latest

- name: Install php8-xml
  become: yes
  apt: pkg=php8.0-xml state=latest

- name: Install php8-fpm
  become: yes
  apt: pkg=php8.0-fpm state=latest

- name: Install php8-curl
  become: yes
  apt: pkg=php8.0-curl state=latest

- name: Install php8-mbstring
  become: yes
  apt: pkg=php8.0-mbstring state=latest

- name: Install php8-bcmath
  become: yes
  apt: pkg=php8.0-bcmath state=latest

- name: Install php8-soap
  become: yes
  apt: pkg=php8.0-soap state=latest

- name: Install php8-gd
  become: yes
  apt: pkg=php8.0-gd state=latest

- name: Install php8-intl
  become: yes
  apt: pkg=php8.0-intl state=latest
