---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install php7.3
  become: yes
  apt: pkg=php7.3 state=latest

- name: Install php7-cli
  become: yes
  apt: pkg=php7.3-cli state=latest

- name: Install php7-zip
  become: yes
  apt: pkg=php7.3-zip state=latest

- name: Install php7-mysql
  become: yes
  apt: pkg=php7.3-mysql state=latest

- name: Install php7-xml
  become: yes
  apt: pkg=php7.3-xml state=latest

- name: Install php7-fpm
  become: yes
  apt: pkg=php7.3-fpm state=latest

- name: Install php7-curl
  become: yes
  apt: pkg=php7.3-curl state=latest

- name: Install php7-mbstring
  become: yes
  apt: pkg=php7.3-mbstring state=latest

- name: Install php7-bcmath
  become: yes
  apt: pkg=php7.3-bcmath state=latest

- name: Install php7-soap
  become: yes
  apt: pkg=php7.3-soap state=latest

- name: Install php7-gd
  become: yes
  apt: pkg=php7.3-gd state=latest

- name: Install php7-intl
  become: yes
  apt: pkg=php7.3-intl state=latest
